package com.gestproj.backend.common.enums;

public enum NotificationType {
  INVITATION_SENT,
  INVITATION_ACCEPTED,
  INVITATION_REJECTED,
  MEMBER_UPDATED,
  MEMBER_STATUS_CHANGED,
  DEPLOYMENT_FAILED,
  DEPLOYMENT_SUCCEEDED
}
