-- Create deployments table
CREATE TABLE deployments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  commit_hash VARCHAR(255),
  commit_message TEXT,
  triggered_by VARCHAR(255),
  started_at TIMESTAMP,
  finished_at TIMESTAMP,
  CONSTRAINT fk_deployments_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX idx_deployments_project_id ON deployments(project_id);
